export const stationList = [
  "Station-1",
  "Station-2",
  "Station-3",
  "Station-4",
  "Station-5",
  "Station-6",
  "Station-7",
  "Station-8",
  "Station-9",
  "Station-10",
  "Station-11",
  "Station-12",
  "Station-13",
  "Station-14",
  "Station-15",
  "Station-16",
  "Station-17",
  "Station-18",
  "Station-19",
  "Station-20",
];

export const blockDistance = [
  { from_station: "Station-1", to_station: "Station-2", distance_km: 12 },
  { from_station: "Station-2", to_station: "Station-3", distance_km: 5 },
  { from_station: "Station-3", to_station: "Station-4", distance_km: 8 },
  { from_station: "Station-4", to_station: "Station-5", distance_km: 14 },
  { from_station: "Station-5", to_station: "Station-6", distance_km: 6 },
  { from_station: "Station-6", to_station: "Station-7", distance_km: 9 },
  { from_station: "Station-7", to_station: "Station-8", distance_km: 7 },
  { from_station: "Station-8", to_station: "Station-9", distance_km: 10 },
  { from_station: "Station-9", to_station: "Station-10", distance_km: 11 },
  { from_station: "Station-10", to_station: "Station-11", distance_km: 13 },
  { from_station: "Station-11", to_station: "Station-12", distance_km: 4 },
  { from_station: "Station-12", to_station: "Station-13", distance_km: 6 },
  { from_station: "Station-13", to_station: "Station-14", distance_km: 8 },
  { from_station: "Station-14", to_station: "Station-15", distance_km: 9 },
  { from_station: "Station-15", to_station: "Station-16", distance_km: 5 },
  { from_station: "Station-16", to_station: "Station-17", distance_km: 7 },
  { from_station: "Station-17", to_station: "Station-18", distance_km: 10 },
  { from_station: "Station-18", to_station: "Station-19", distance_km: 8 },
  { from_station: "Station-19", to_station: "Station-20", distance_km: 8 },
];

// export const stationDistance = [
//   { station: "Station-1", km_from_start: 0 },
//   { station: "Station-2", km_from_start: 12 },
//   { station: "Station-3", km_from_start: 17 },
//   { station: "Station-4", km_from_start: 25 },
//   { station: "Station-5", km_from_start: 39 },
//   { station: "Station-6", km_from_start: 45 },
//   { station: "Station-7", km_from_start: 54 },
//   { station: "Station-8", km_from_start: 61 }, 
//   { station: "Station-9", km_from_start: 71 },
//   { station: "Station-10", km_from_start: 82 },
//   { station: "Station-11", km_from_start: 95 },
//   { station: "Station-12", km_from_start: 99 },
//   { station: "Station-13", km_from_start: 105 },
//   { station: "Station-14", km_from_start: 113 },
//   { station: "Station-15", km_from_start: 122 },
//   { station: "Station-16", km_from_start: 127 },
//   { station: "Station-17", km_from_start: 134 },
//   { station: "Station-18", km_from_start: 144 },
//   { station: "Station-19", km_from_start: 152 },
//   { station: "Station-20", km_from_start: 160 },
// ];

export const stationDistance = [
  { station: "KTV", km_from_start: 0 },
  { station: "KPL", km_from_start: 7.74 },
  { station: "ALM", km_from_start: 16.97 },
  { station: "KUK", km_from_start: 24.08 },
  { station: "VZM", km_from_start: 34.73 },
  { station: "NML", km_from_start: 46.47 },
  { station: "GVI", km_from_start: 58.7 },
  { station: "CPP", km_from_start: 65.37 },
  { station: "BTVA", km_from_start: 69.8 },
  { station: "SGDM", km_from_start: 78.64 },
  { station: "PDU", km_from_start: 88.71 },
  { station: "DUSI", km_from_start: 97.53 },
  { station: "CHE", km_from_start: 103.99 },
  { station: "ULM", km_from_start: 114.03 },
  { station: "TIU", km_from_start: 123.66 },
  { station: "HCM", km_from_start: 129.09 },
  { station: "KBM", km_from_start: 137.38 },
  { station: "DGB", km_from_start: 145.36 },
  { station: "NWP", km_from_start: 151.3 },
  { station: "RMZ", km_from_start: 158.31 },
  { station: "PUN", km_from_start: 164.54 },
  { station: "PSA", km_from_start: 176.83 },
];

export const trainDataset = [
  /*
  ==========================================================
  TRAIN 1 — UP (freight)
  ==========================================================
  */
  {
    train_id: "T1",
    train_name: "Train 1 UP",
    train_type: "freight",
    color: "#e41a1c",
    segments: [
      {
        from_station: "Station-1",
        to_station: "Station-2",
        distance_km: 12,
        scheduled_dep: "01:00",
        scheduled_arr: "01:45",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-2",
        to_station: "Station-3",
        distance_km: 5,
        scheduled_dep: "01:05",
        scheduled_arr: "01:10",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-3",
        to_station: "Station-4",
        distance_km: 8,
        scheduled_dep: "01:10",
        scheduled_arr: "01:15",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-4",
        to_station: "Station-5",
        distance_km: 14,
        scheduled_dep: "01:15",
        scheduled_arr: "01:20",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-5",
        to_station: "Station-6",
        distance_km: 6,
        scheduled_dep: "01:20",
        scheduled_arr: "01:25",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-6",
        to_station: "Station-7",
        distance_km: 9,
        scheduled_dep: "01:25",
        scheduled_arr: "01:30",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-7",
        to_station: "Station-8",
        distance_km: 7,
        scheduled_dep: "01:30",
        scheduled_arr: "01:35",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-8",
        to_station: "Station-9",
        distance_km: 10,
        scheduled_dep: "01:35",
        scheduled_arr: "01:40",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-9",
        to_station: "Station-10",
        distance_km: 11,
        scheduled_dep: "01:40",
        scheduled_arr: "01:45",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-10",
        to_station: "Station-11",
        distance_km: 13,
        scheduled_dep: "01:45",
        scheduled_arr: "01:50",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-11",
        to_station: "Station-12",
        distance_km: 4,
        scheduled_dep: "01:50",
        scheduled_arr: "01:55",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-12",
        to_station: "Station-13",
        distance_km: 6,
        scheduled_dep: "01:55",
        scheduled_arr: "02:00",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-13",
        to_station: "Station-14",
        distance_km: 8,
        scheduled_dep: "02:00",
        scheduled_arr: "02:05",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-14",
        to_station: "Station-15",
        distance_km: 9,
        scheduled_dep: "02:05",
        scheduled_arr: "02:10",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-15",
        to_station: "Station-16",
        distance_km: 5,
        scheduled_dep: "02:10",
        scheduled_arr: "02:15",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-16",
        to_station: "Station-17",
        distance_km: 7,
        scheduled_dep: "02:15",
        scheduled_arr: "02:20",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-17",
        to_station: "Station-18",
        distance_km: 10,
        scheduled_dep: "02:20",
        scheduled_arr: "02:25",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-18",
        to_station: "Station-19",
        distance_km: 8,
        scheduled_dep: "02:25",
        scheduled_arr: "02:30",
        dwell_time_sec: 30,
      },
      {
        from_station: "Station-19",
        to_station: "Station-20",
        distance_km: 8,
        scheduled_dep: "02:30",
        scheduled_arr: "02:35",
        dwell_time_sec: 30,
      },
    ],
  },

  /*
  ==========================================================
  TRAIN 2 — UP (freight)
  ==========================================================
  */
  {
    train_id: "T2",
    train_name: "Train 2 UP",
    train_type: "freight",
    color: "#377eb8",
    segments: [
      {
        from_station: "Station-1",
        to_station: "Station-2",
        distance_km: 12,
        scheduled_dep: "02:00",
        scheduled_arr: "02:04",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-2",
        to_station: "Station-3",
        distance_km: 5,
        scheduled_dep: "02:04",
        scheduled_arr: "02:08",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-3",
        to_station: "Station-4",
        distance_km: 8,
        scheduled_dep: "02:08",
        scheduled_arr: "02:12",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-4",
        to_station: "Station-5",
        distance_km: 14,
        scheduled_dep: "02:12",
        scheduled_arr: "02:16",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-5",
        to_station: "Station-6",
        distance_km: 6,
        scheduled_dep: "02:16",
        scheduled_arr: "02:20",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-6",
        to_station: "Station-7",
        distance_km: 9,
        scheduled_dep: "02:20",
        scheduled_arr: "02:24",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-7",
        to_station: "Station-8",
        distance_km: 7,
        scheduled_dep: "02:24",
        scheduled_arr: "02:28",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-8",
        to_station: "Station-9",
        distance_km: 10,
        scheduled_dep: "02:28",
        scheduled_arr: "02:32",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-9",
        to_station: "Station-10",
        distance_km: 11,
        scheduled_dep: "02:32",
        scheduled_arr: "02:36",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-10",
        to_station: "Station-11",
        distance_km: 13,
        scheduled_dep: "02:36",
        scheduled_arr: "02:40",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-11",
        to_station: "Station-12",
        distance_km: 4,
        scheduled_dep: "02:40",
        scheduled_arr: "02:44",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-12",
        to_station: "Station-13",
        distance_km: 6,
        scheduled_dep: "02:44",
        scheduled_arr: "02:48",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-13",
        to_station: "Station-14",
        distance_km: 8,
        scheduled_dep: "02:48",
        scheduled_arr: "02:52",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-14",
        to_station: "Station-15",
        distance_km: 9,
        scheduled_dep: "02:52",
        scheduled_arr: "02:56",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-15",
        to_station: "Station-16",
        distance_km: 5,
        scheduled_dep: "02:56",
        scheduled_arr: "03:00",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-16",
        to_station: "Station-17",
        distance_km: 7,
        scheduled_dep: "03:00",
        scheduled_arr: "03:04",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-17",
        to_station: "Station-18",
        distance_km: 10,
        scheduled_dep: "03:04",
        scheduled_arr: "03:08",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-18",
        to_station: "Station-19",
        distance_km: 8,
        scheduled_dep: "03:08",
        scheduled_arr: "03:12",
        dwell_time_sec: 20,
      },
      {
        from_station: "Station-19",
        to_station: "Station-20",
        distance_km: 8,
        scheduled_dep: "03:12",
        scheduled_arr: "03:16",
        dwell_time_sec: 20,
      },
    ],
  },

  /*
  ==========================================================
  TRAIN 3 — UP (PASSENGER)
  ==========================================================
  */
  {
    train_id: "T3",
    train_name: "Train 3 UP",
    train_type: "passenger",
    color: "#4daf4a",
    segments: [
      {
        from_station: "Station-1",
        to_station: "Station-2",
        distance_km: 12,
        scheduled_dep: "03:00",
        scheduled_arr: "03:03",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-2",
        to_station: "Station-3",
        distance_km: 5,
        scheduled_dep: "03:03",
        scheduled_arr: "03:06",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-3",
        to_station: "Station-4",
        distance_km: 8,
        scheduled_dep: "03:06",
        scheduled_arr: "03:09",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-4",
        to_station: "Station-5",
        distance_km: 14,
        scheduled_dep: "03:09",
        scheduled_arr: "03:12",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-5",
        to_station: "Station-6",
        distance_km: 6,
        scheduled_dep: "03:12",
        scheduled_arr: "03:15",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-6",
        to_station: "Station-7",
        distance_km: 9,
        scheduled_dep: "03:15",
        scheduled_arr: "03:18",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-7",
        to_station: "Station-8",
        distance_km: 7,
        scheduled_dep: "03:18",
        scheduled_arr: "03:21",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-8",
        to_station: "Station-9",
        distance_km: 10,
        scheduled_dep: "03:21",
        scheduled_arr: "03:24",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-9",
        to_station: "Station-10",
        distance_km: 11,
        scheduled_dep: "03:24",
        scheduled_arr: "03:27",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-10",
        to_station: "Station-11",
        distance_km: 13,
        scheduled_dep: "03:27",
        scheduled_arr: "03:30",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-11",
        to_station: "Station-12",
        distance_km: 4,
        scheduled_dep: "03:30",
        scheduled_arr: "03:33",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-12",
        to_station: "Station-13",
        distance_km: 6,
        scheduled_dep: "03:33",
        scheduled_arr: "03:36",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-13",
        to_station: "Station-14",
        distance_km: 8,
        scheduled_dep: "03:36",
        scheduled_arr: "03:39",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-14",
        to_station: "Station-15",
        distance_km: 9,
        scheduled_dep: "03:39",
        scheduled_arr: "03:42",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-15",
        to_station: "Station-16",
        distance_km: 5,
        scheduled_dep: "03:42",
        scheduled_arr: "03:45",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-16",
        to_station: "Station-17",
        distance_km: 7,
        scheduled_dep: "03:45",
        scheduled_arr: "03:48",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-17",
        to_station: "Station-18",
        distance_km: 10,
        scheduled_dep: "03:48",
        scheduled_arr: "03:51",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-18",
        to_station: "Station-19",
        distance_km: 8,
        scheduled_dep: "03:51",
        scheduled_arr: "03:54",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-19",
        to_station: "Station-20",
        distance_km: 8,
        scheduled_dep: "03:54",
        scheduled_arr: "03:57",
        dwell_time_sec: 0,
      },
    ],
  },

  /*
  ==========================================================
  TRAIN 4 — DOWN (PASSENGER)
  ==========================================================
  */
  {
    train_id: "T4",
    train_name: "Train 4 DOWN",
    train_type: "passenger",
    color: "#984ea3",
    segments: [
      {
        from_station: "Station-20",
        to_station: "Station-19",
        distance_km: 8,
        scheduled_dep: "00:00",
        scheduled_arr: "00:03",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-19",
        to_station: "Station-18",
        distance_km: 8,
        scheduled_dep: "00:03",
        scheduled_arr: "00:06",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-18",
        to_station: "Station-17",
        distance_km: 10,
        scheduled_dep: "00:06",
        scheduled_arr: "00:09",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-17",
        to_station: "Station-16",
        distance_km: 7,
        scheduled_dep: "00:09",
        scheduled_arr: "00:12",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-16",
        to_station: "Station-15",
        distance_km: 5,
        scheduled_dep: "00:12",
        scheduled_arr: "00:15",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-15",
        to_station: "Station-14",
        distance_km: 9,
        scheduled_dep: "00:15",
        scheduled_arr: "00:18",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-14",
        to_station: "Station-13",
        distance_km: 8,
        scheduled_dep: "00:18",
        scheduled_arr: "00:21",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-13",
        to_station: "Station-12",
        distance_km: 6,
        scheduled_dep: "00:21",
        scheduled_arr: "00:24",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-12",
        to_station: "Station-11",
        distance_km: 4,
        scheduled_dep: "00:24",
        scheduled_arr: "00:27",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-11",
        to_station: "Station-10",
        distance_km: 13,
        scheduled_dep: "00:27",
        scheduled_arr: "00:30",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-10",
        to_station: "Station-9",
        distance_km: 11,
        scheduled_dep: "00:30",
        scheduled_arr: "00:33",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-9",
        to_station: "Station-8",
        distance_km: 10,
        scheduled_dep: "00:33",
        scheduled_arr: "00:36",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-8",
        to_station: "Station-7",
        distance_km: 7,
        scheduled_dep: "00:36",
        scheduled_arr: "00:39",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-7",
        to_station: "Station-6",
        distance_km: 9,
        scheduled_dep: "00:39",
        scheduled_arr: "00:42",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-6",
        to_station: "Station-5",
        distance_km: 6,
        scheduled_dep: "00:42",
        scheduled_arr: "00:45",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-5",
        to_station: "Station-4",
        distance_km: 14,
        scheduled_dep: "00:45",
        scheduled_arr: "00:48",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-4",
        to_station: "Station-3",
        distance_km: 8,
        scheduled_dep: "00:48",
        scheduled_arr: "00:51",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-3",
        to_station: "Station-2",
        distance_km: 5,
        scheduled_dep: "00:51",
        scheduled_arr: "00:54",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-2",
        to_station: "Station-1",
        distance_km: 12,
        scheduled_dep: "00:54",
        scheduled_arr: "00:57",
        dwell_time_sec: 0,
      },
    ],
  },

  /*
  ==========================================================
  TRAIN 5 — DOWN (FREIGHT)
  ==========================================================
  */
  {
    train_id: "T5",
    train_name: "Train 5 DOWN",
    train_type: "freight",
    color: "#ff7f00",
    segments: [
      {
        from_station: "Station-20",
        to_station: "Station-19",
        distance_km: 8,
        scheduled_dep: "01:00",
        scheduled_arr: "01:05",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-19",
        to_station: "Station-18",
        distance_km: 8,
        scheduled_dep: "01:05",
        scheduled_arr: "01:10",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-18",
        to_station: "Station-17",
        distance_km: 10,
        scheduled_dep: "01:10",
        scheduled_arr: "01:15",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-17",
        to_station: "Station-16",
        distance_km: 7,
        scheduled_dep: "01:15",
        scheduled_arr: "01:20",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-16",
        to_station: "Station-15",
        distance_km: 5,
        scheduled_dep: "01:20",
        scheduled_arr: "01:25",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-15",
        to_station: "Station-14",
        distance_km: 9,
        scheduled_dep: "01:25",
        scheduled_arr: "01:30",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-14",
        to_station: "Station-13",
        distance_km: 8,
        scheduled_dep: "01:30",
        scheduled_arr: "01:35",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-13",
        to_station: "Station-12",
        distance_km: 6,
        scheduled_dep: "01:35",
        scheduled_arr: "01:40",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-12",
        to_station: "Station-11",
        distance_km: 4,
        scheduled_dep: "01:40",
        scheduled_arr: "01:45",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-11",
        to_station: "Station-10",
        distance_km: 13,
        scheduled_dep: "01:45",
        scheduled_arr: "01:50",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-10",
        to_station: "Station-9",
        distance_km: 11,
        scheduled_dep: "01:50",
        scheduled_arr: "01:55",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-9",
        to_station: "Station-8",
        distance_km: 10,
        scheduled_dep: "01:55",
        scheduled_arr: "02:00",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-8",
        to_station: "Station-7",
        distance_km: 7,
        scheduled_dep: "02:00",
        scheduled_arr: "02:05",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-7",
        to_station: "Station-6",
        distance_km: 9,
        scheduled_dep: "02:05",
        scheduled_arr: "02:10",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-6",
        to_station: "Station-5",
        distance_km: 6,
        scheduled_dep: "02:10",
        scheduled_arr: "02:15",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-5",
        to_station: "Station-4",
        distance_km: 14,
        scheduled_dep: "02:15",
        scheduled_arr: "02:20",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-4",
        to_station: "Station-3",
        distance_km: 8,
        scheduled_dep: "02:20",
        scheduled_arr: "02:25",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-3",
        to_station: "Station-2",
        distance_km: 5,
        scheduled_dep: "02:25",
        scheduled_arr: "02:30",
        dwell_time_sec: 0,
      },
      {
        from_station: "Station-2",
        to_station: "Station-1",
        distance_km: 12,
        scheduled_dep: "02:30",
        scheduled_arr: "02:35",
        dwell_time_sec: 0,
      },
    ],
  },
];
